// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHiFSJ1GWa2sMT--_j4hhsSYiNB9FifJA',
    appId: '1:708652857000:web:09a55f4d99c8e68077749d',
    messagingSenderId: '708652857000',
    projectId: 'myapp-24fa5',
    authDomain: 'myapp-24fa5.firebaseapp.com',
    storageBucket: 'myapp-24fa5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWVk1rtreoL_dwhBGCJdehtbrq1xCmF-s',
    appId: '1:708652857000:android:75447ab6428bb7f477749d',
    messagingSenderId: '708652857000',
    projectId: 'myapp-24fa5',
    storageBucket: 'myapp-24fa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClC3Br5VMlopM-aU7yiEsR1qXk5jnanDY',
    appId: '1:708652857000:ios:5fce7d906f50a25c77749d',
    messagingSenderId: '708652857000',
    projectId: 'myapp-24fa5',
    storageBucket: 'myapp-24fa5.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHiFSJ1GWa2sMT--_j4hhsSYiNB9FifJA',
    appId: '1:708652857000:web:3cbd5ac3a5851eda77749d',
    messagingSenderId: '708652857000',
    projectId: 'myapp-24fa5',
    authDomain: 'myapp-24fa5.firebaseapp.com',
    storageBucket: 'myapp-24fa5.appspot.com',
  );
}
